name: building the golang application

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Adding the Go Language     
        uses: actions/setup-go@v5
        with: 
          go-version: 1.22.4
      - name: Build the Go language
        uses: actions/github-script@v7
        with: 
          script: |
            go mod tidy
            go build -o myapp
      - name: Publishing the artifacts
        uses: actions/upload-artifact@v4            
        with:
          name: myapp
          path: ${{ github.workspace }}/myapp
